openapi: 3.1.0
info:
  title: A test spec
  version: '1'
paths:
  /foo:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FooPostRequest'
      responses:
        '204':
          description: OK
components:
  schemas:
    FooPostRequest:
      properties:
        bar:
          type: string
